apiVersion: v1
kind: Pod
metadata:
  annotations:
    hub.jupyter.org/username: pytest
  creationTimestamp: "2022-04-18T11:19:21Z"
  labels:
    app: jupyterhub
    chart: jupyterhub-1.2.0
    component: singleuser-server
    heritage: jupyterhub
    hub.jupyter.org/network-access-hub: "true"
    hub.jupyter.org/servername: ""
    hub.jupyter.org/username: pytest
    release: release
  name: jupyter-pytest
  namespace: default
  resourceVersion: "32454451"
  uid: ea30f95a-658a-43a6-abda-aa047dd287bf
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: hub.jupyter.org/node-purpose
            operator: In
            values:
            - user
        weight: 100
  automountServiceAccountToken: false
  containers:
  - args:
    - jupyterhub-singleuser
    - --ip=0.0.0.0
    - --port=8888
    env:
    - name: CPU_GUARANTEE
      value: "0.2"
    - name: CPU_LIMIT
      value: "0.4"
    - name: JPY_API_TOKEN
      value: ec5885675b1740579d4f9fe3c3378b0c
    - name: JUPYTERHUB_ACTIVITY_URL
      value: http://hub:8081/hub/api/users/pytest/activity
    - name: JUPYTERHUB_ADMIN_ACCESS
      value: "1"
    - name: JUPYTERHUB_API_TOKEN
      value: ec5885675b1740579d4f9fe3c3378b0c
    - name: JUPYTERHUB_API_URL
      value: http://hub:8081/hub/api
    - name: JUPYTERHUB_BASE_URL
      value: /
    - name: JUPYTERHUB_CLIENT_ID
      value: jupyterhub-user-pytest
    - name: JUPYTERHUB_HOST
    - name: JUPYTERHUB_OAUTH_CALLBACK_URL
      value: /user/pytest/oauth_callback
    - name: JUPYTERHUB_SERVER_NAME
    - name: JUPYTERHUB_SERVICE_PREFIX
      value: /user/pytest/
    - name: JUPYTERHUB_USER
      value: pytest
    - name: JUPYTER_IMAGE
      value: jupyterhub/k8s-singleuser-sample:1.2.0
    - name: JUPYTER_IMAGE_SPEC
      value: jupyterhub/k8s-singleuser-sample:1.2.0
    - name: MEM_GUARANTEE
      value: "536870912"
    - name: MEM_LIMIT
      value: "1073741824"
    image: jupyterhub/k8s-singleuser-sample:1.2.0
    imagePullPolicy: IfNotPresent
    lifecycle: {}
    name: notebook
    ports:
    - containerPort: 8888
      name: notebook-port
      protocol: TCP
    resources:
      limits:
        cpu: 400m
        memory: "1073741824"
      requests:
        cpu: 200m
        memory: "536870912"
    securityContext:
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/jovyan
      name: volume-pytest
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - iptables
    - -A
    - OUTPUT
    - -d
    - 169.254.169.254
    - -j
    - DROP
    image: jupyterhub/k8s-network-tools:1.2.0
    imagePullPolicy: IfNotPresent
    name: block-cloud-metadata
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeName: gke-maincluster-default-pool-2bf650f6-cvxp
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: release-user-scheduler
  securityContext:
    fsGroup: 100
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: hub.jupyter.org/dedicated
    operator: Equal
    value: user
  - effect: NoSchedule
    key: hub.jupyter.org_dedicated
    operator: Equal
    value: user
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: volume-pytest
    persistentVolumeClaim:
      claimName: claim-pytest
status:
  conditions:
  - lastProbeTime:
    lastTransitionTime: "2022-04-18T11:19:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime:
    lastTransitionTime: "2022-04-18T11:19:40Z"
    status: "True"
    type: Ready
  - lastProbeTime:
    lastTransitionTime: "2022-04-18T11:19:40Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime:
    lastTransitionTime: "2022-04-18T11:19:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://8ad001dc6812dcaba89aea21fdf4cb075b91c4a1092fdb000dddcd78a960d710
    image: docker.io/jupyterhub/k8s-singleuser-sample:1.2.0
    imageID: docker.io/jupyterhub/k8s-singleuser-sample@sha256:7fba974bb151a3bd5bcdb33e12a9be146274de44fec47ffc64345144d403400d
    lastState: {}
    name: notebook
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-04-18T11:19:39Z"
  hostIP: 10.156.0.8
  initContainerStatuses:
  - containerID: containerd://9a40843366a5c2bd13edc72a7ef8b984d1ed663e1e3dff60b414a5e9ffed3f22
    image: docker.io/jupyterhub/k8s-network-tools:1.2.0
    imageID: docker.io/jupyterhub/k8s-network-tools@sha256:a6fa68b84748dcf01085016fd2475e84a38d4b5f0940d010c0ae3044e50ee28d
    lastState: {}
    name: block-cloud-metadata
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://9a40843366a5c2bd13edc72a7ef8b984d1ed663e1e3dff60b414a5e9ffed3f22
        exitCode: 0
        finishedAt: "2022-04-18T11:19:39Z"
        reason: Completed
        startedAt: "2022-04-18T11:19:39Z"
  phase: Running
  podIP: 10.96.0.31
  podIPs:
  - ip: 10.96.0.31
  qosClass: Burstable
  startTime: "2022-04-18T11:19:21Z"
