apiVersion: v1
kind: Pod
metadata:
  annotations:
    hub.jupyter.org/username: sander
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"hub.jupyter.org/username":"sander"},"creationTimestamp":"2022-04-08T14:49:23Z","labels":{"app":"jupyterhub","chart":"jupyterhub-1.2.0","component":"singleuser-server","heritage":"jupyterhub","hub.jupyter.org/network-access-hub":"true","hub.jupyter.org/servername":"","hub.jupyter.org/username":"sander","release":"release"},"name":"jupyter-sander","namespace":"default","resourceVersion":"26170610","uid":"745856ea-9023-47bc-897d-06ac1512a102"},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"hub.jupyter.org/node-purpose","operator":"In","values":["user"]}]},"weight":100}]}},"automountServiceAccountToken":false,"containers":[{"args":["jupyterhub-singleuser","--ip=0.0.0.0","--port=8888"],"env":[{"name":"CPU_GUARANTEE","value":"0.1"},{"name":"CPU_LIMIT","value":"0.2"},{"name":"JPY_API_TOKEN","value":"66af8214c80e4a429c5b4862f135d500"},{"name":"JUPYTERHUB_ACTIVITY_URL","value":"http://hub:8081/hub/api/users/sander/activity"},{"name":"JUPYTERHUB_ADMIN_ACCESS","value":"1"},{"name":"JUPYTERHUB_API_TOKEN","value":"66af8214c80e4a429c5b4862f135d500"},{"name":"JUPYTERHUB_API_URL","value":"http://hub:8081/hub/api"},{"name":"JUPYTERHUB_BASE_URL","value":"/"},{"name":"JUPYTERHUB_CLIENT_ID","value":"jupyterhub-user-sander"},{"name":"JUPYTERHUB_HOST"},{"name":"JUPYTERHUB_OAUTH_CALLBACK_URL","value":"/user/sander/oauth_callback"},{"name":"JUPYTERHUB_SERVER_NAME"},{"name":"JUPYTERHUB_SERVICE_PREFIX","value":"/user/sander/"},{"name":"JUPYTERHUB_USER","value":"sander"},{"name":"JUPYTER_IMAGE","value":"jupyterhub/k8s-singleuser-sample:1.2.0"},{"name":"JUPYTER_IMAGE_SPEC","value":"jupyterhub/k8s-singleuser-sample:1.2.0"},{"name":"MEM_GUARANTEE","value":"536870912"},{"name":"MEM_LIMIT","value":"1073741824"}],"image":"jupyterhub/k8s-singleuser-sample:1.2.0","imagePullPolicy":"IfNotPresent","lifecycle":{},"name":"notebook","ports":[{"containerPort":8888,"name":"notebook-port","protocol":"TCP"}],"resources":{"limits":{"cpu":"200m","memory":"1073741824"},"requests":{"cpu":"100m","memory":"536870912"}},"securityContext":{"runAsUser":1000},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/home/jovyan","name":"volume-sander"}]}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"initContainers":[{"command":["iptables","-A","OUTPUT","-d","169.254.169.254","-j","DROP"],"image":"jupyterhub/k8s-network-tools:1.2.0","imagePullPolicy":"IfNotPresent","name":"block-cloud-metadata","resources":{},"securityContext":{"capabilities":{"add":["NET_ADMIN"]},"privileged":true,"runAsUser":0},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"nodeName":"gke-maincluster-default-pool-2bf650f6-cvxp","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"OnFailure","schedulerName":"release-user-scheduler","securityContext":{"fsGroup":100},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"hub.jupyter.org/dedicated","operator":"Equal","value":"user"},{"effect":"NoSchedule","key":"hub.jupyter.org_dedicated","operator":"Equal","value":"user"},{"effect":"NoExecute","key":"node.kubernetes.io/not-ready","operator":"Exists","tolerationSeconds":300},{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":300}],"volumes":[{"name":"volume-sander","persistentVolumeClaim":{"claimName":"claim-sander"}}]},"status":{"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2022-04-08T14:50:29Z","status":"True","type":"Initialized"},{"lastProbeTime":null,"lastTransitionTime":"2022-04-08T14:50:30Z","status":"True","type":"Ready"},{"lastProbeTime":null,"lastTransitionTime":"2022-04-08T14:50:30Z","status":"True","type":"ContainersReady"},{"lastProbeTime":null,"lastTransitionTime":"2022-04-08T14:49:23Z","status":"True","type":"PodScheduled"}],"containerStatuses":[{"containerID":"containerd://ab639b79911cbf62c160b00b38dba174bfaee038de46c3f47a4f4a43cc77f147","image":"docker.io/jupyterhub/k8s-singleuser-sample:1.2.0","imageID":"docker.io/jupyterhub/k8s-singleuser-sample@sha256:7fba974bb151a3bd5bcdb33e12a9be146274de44fec47ffc64345144d403400d","lastState":{},"name":"notebook","ready":true,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2022-04-08T14:50:29Z"}}}],"hostIP":"10.156.0.6","initContainerStatuses":[{"containerID":"containerd://c851c1578ec9f5136cb92b2f64cd25c03b111bca5a41a08f994244c1f61b32e4","image":"docker.io/jupyterhub/k8s-network-tools:1.2.0","imageID":"docker.io/jupyterhub/k8s-network-tools@sha256:a6fa68b84748dcf01085016fd2475e84a38d4b5f0940d010c0ae3044e50ee28d","lastState":{},"name":"block-cloud-metadata","ready":true,"restartCount":0,"state":{"terminated":{"containerID":"containerd://c851c1578ec9f5136cb92b2f64cd25c03b111bca5a41a08f994244c1f61b32e4","exitCode":0,"finishedAt":"2022-04-08T14:50:28Z","reason":"Completed","startedAt":"2022-04-08T14:50:28Z"}}}],"phase":"Running","podIP":"10.96.0.49","podIPs":[{"ip":"10.96.0.49"}],"qosClass":"Burstable","startTime":"2022-04-08T14:49:23Z"}}
  creationTimestamp: "2022-04-08T14:49:23Z"
  labels:
    app: jupyterhub
    chart: jupyterhub-1.2.0
    component: singleuser-server
    heritage: jupyterhub
    hub.jupyter.org/network-access-hub: "true"
    hub.jupyter.org/servername: ""
    hub.jupyter.org/username: sander
    release: release
  name: jupyter-sander
  namespace: default
  resourceVersion: "26171255"
  uid: 745856ea-9023-47bc-897d-06ac1512a102
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: hub.jupyter.org/node-purpose
            operator: In
            values:
            - user
        weight: 100
  automountServiceAccountToken: false
  containers:
  - args:
    - jupyterhub-singleuser
    - --ip=0.0.0.0
    - --port=8888
    env:
    - name: CPU_GUARANTEE
      value: "0.2"
    - name: CPU_LIMIT
      value: "0.4"
    - name: JPY_API_TOKEN
      value: 66af8214c80e4a429c5b4862f135d500
    - name: JUPYTERHUB_ACTIVITY_URL
      value: http://hub:8081/hub/api/users/sander/activity
    - name: JUPYTERHUB_ADMIN_ACCESS
      value: "1"
    - name: JUPYTERHUB_API_TOKEN
      value: 66af8214c80e4a429c5b4862f135d500
    - name: JUPYTERHUB_API_URL
      value: http://hub:8081/hub/api
    - name: JUPYTERHUB_BASE_URL
      value: /
    - name: JUPYTERHUB_CLIENT_ID
      value: jupyterhub-user-sander
    - name: JUPYTERHUB_HOST
    - name: JUPYTERHUB_OAUTH_CALLBACK_URL
      value: /user/sander/oauth_callback
    - name: JUPYTERHUB_SERVER_NAME
    - name: JUPYTERHUB_SERVICE_PREFIX
      value: /user/sander/
    - name: JUPYTERHUB_USER
      value: sander
    - name: JUPYTER_IMAGE
      value: jupyterhub/k8s-singleuser-sample:1.2.0
    - name: JUPYTER_IMAGE_SPEC
      value: jupyterhub/k8s-singleuser-sample:1.2.0
    - name: MEM_GUARANTEE
      value: "536870912"
    - name: MEM_LIMIT
      value: "1073741824"
    image: jupyterhub/k8s-singleuser-sample:1.2.0
    imagePullPolicy: IfNotPresent
    lifecycle: {}
    name: notebook
    ports:
    - containerPort: 8888
      name: notebook-port
      protocol: TCP
    resources:
      limits:
        cpu: 400m
        memory: "1073741824"
      requests:
        cpu: 200m
        memory: "536870912"
    securityContext:
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/jovyan
      name: volume-sander
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - iptables
    - -A
    - OUTPUT
    - -d
    - 169.254.169.254
    - -j
    - DROP
    image: jupyterhub/k8s-network-tools:1.2.0
    imagePullPolicy: IfNotPresent
    name: block-cloud-metadata
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeName: gke-maincluster-default-pool-2bf650f6-cvxp
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: release-user-scheduler
  securityContext:
    fsGroup: 100
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: hub.jupyter.org/dedicated
    operator: Equal
    value: user
  - effect: NoSchedule
    key: hub.jupyter.org_dedicated
    operator: Equal
    value: user
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: volume-sander
    persistentVolumeClaim:
      claimName: claim-sander
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-04-08T14:50:29Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-04-08T14:50:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-04-08T14:50:30Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-04-08T14:49:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://ab639b79911cbf62c160b00b38dba174bfaee038de46c3f47a4f4a43cc77f147
    image: docker.io/jupyterhub/k8s-singleuser-sample:1.2.0
    imageID: docker.io/jupyterhub/k8s-singleuser-sample@sha256:7fba974bb151a3bd5bcdb33e12a9be146274de44fec47ffc64345144d403400d
    lastState: {}
    name: notebook
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-04-08T14:50:29Z"
  hostIP: 10.156.0.6
  initContainerStatuses:
  - containerID: containerd://c851c1578ec9f5136cb92b2f64cd25c03b111bca5a41a08f994244c1f61b32e4
    image: docker.io/jupyterhub/k8s-network-tools:1.2.0
    imageID: docker.io/jupyterhub/k8s-network-tools@sha256:a6fa68b84748dcf01085016fd2475e84a38d4b5f0940d010c0ae3044e50ee28d
    lastState: {}
    name: block-cloud-metadata
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://c851c1578ec9f5136cb92b2f64cd25c03b111bca5a41a08f994244c1f61b32e4
        exitCode: 0
        finishedAt: "2022-04-08T14:50:28Z"
        reason: Completed
        startedAt: "2022-04-08T14:50:28Z"
  phase: Running
  podIP: 10.96.0.49
  podIPs:
  - ip: 10.96.0.49
  qosClass: Burstable
  startTime: "2022-04-08T14:49:23Z"
