apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-container
  template:
    metadata:
      labels:
        app: vpa-container
    spec:
      containers:
      - name: vpa-container
        image: jupyterhub/k8s-singleuser-sample:1.2.0
        ports:
        - containerPort: 8888
        volumeMounts:
        - mountPath: /workloads
          name: workloads
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 200Mi
            cpu: 100m
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            for i in $(seq 100)
            do
                export i
                timeout 40 /bin/bash -c -- 'while true; do echo $i; sleep_time=$(printf "0.%05ds" $((100000/(2**$i)))); sleep ${sleep_time}; done;'
            done
      volumes:
      - name: workloads
        hostPath:
          path: /home/sander/Documents/itu/6_sem/bachelor/kube_vpa/workloads/
