apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-container
  template:
    metadata:
      labels:
        app: vpa-container
    spec:
      containers:
      - name: vpa-container
        image: jupyterhub/k8s-singleuser-sample:1.2.0
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: workloads-volume
          mountPath: /home/jovyan/workloads
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 200Mi
            cpu: 100m
        command: ["/bin/bash"]
        args:
          - "-c"
          - "bash workloads/WORKLOAD_NAME.sh"
      volumes:
      - name: workloads-volume
        configMap:
          name: workloads